# Generated by Django 2.2.2 on 2019-06-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='sentiments',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='word',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
